version: '3'

services:
    server:
        image: node:latest
        container_name: test_server
        network_mode: 'host'
        restart: 'always'
        working_dir: /home/node/app
        command: yarn dev
        volumes:
            - ./:/home/node/app
    database:
        image: postgres:latest
        container_name: test_postgres
        network_mode: 'host'
        environment:
            - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
